### ISSUE TITLE
RFQ - Use bulk add for the CLI command ./craft elastic/elements/index

### ISSUE THREAD

**Issue by lenvanessen** [codemonauts/craft-elasticsearch#1]
Hi There,

We've stared using your plugin, but we have roughly 150k articles it has to index. Because it creates one single job for each article, it takes a long time do the first indexation. Same goes if we want to change/optimize the index, it takes long.

Would it be possible to do the CLI command with batches, rather then the single jobs?

**Comment by kringkaste** [comment]
Hi @lenvanessen, we will shortly implement this. We find the solution with the jobs better especially with a large amount of elements (in case of an error not everything has to be repeated, several workers can process the jobs in parallel), but we understand the wish for a console command.

**Comment by kringkaste** [comment]
Hi @lenvanessen , we just released 1.2.0 (Craft 3 ) and 2.0.0 (Craft 4) with the requested indexation without using jobs and queues. You run the command with `./craft elastic/elements/index "*" 0`. Please test this.

**Comment by lenvanessen** [comment]
@kringkaste I've just tested it, and it works!
