### ISSUE TITLE
Zero results returned

### ISSUE THREAD

**Issue by lenvanessen** [codemonauts/craft-elasticsearch#3]
Hi There,

We're getting zero results from, after examining it seems there is a problem with the search query that is generated by the Elements service.

"SearchTerm" is converted to "*+SearchTerm*" but that returns 0 results.
`
 $params = [
            'index' => $indexes->getIndexName($site),
            'body' => [
                'size' => 10000,
                'query' => [
                    'bool' => [
                        'must' => [
                            'query_string' => [
                                'fields' => $fields,
                                'query' => implode(' ', $queryTokens),
                            ],
                        ],
                    ],
                ],
            ],
        ];
        `
        
However, "* +SearchTerm*" with a space in front returns results. In any case, its arguablly not needed to add the + operator, since the query is already nested within a "must" array key.

**Comment by lenvanessen** [comment]
FYI, we're currently using this repo and branch, and then it works for us:
https://github.com/lenvanessen/craft-elasticsearch/commit/6a1fa819086818c25a5857740b9bdb0172a55470

Any ideas?

**Comment by lenvanessen** [comment]
In any case, it would be nice if we could include an event here:
https://github.com/codemonauts/craft-elasticsearch/blob/main/src/services/Elements.php#L164

So people can mutate the payload that is sent to Elastic, for better control. If you wan't I can whip up a pr!

**Comment by ddnetters** [comment]
The ability to mutate payload without having to fork the plugin would be great

**Comment by kringkaste** [comment]
Sorry for the late response. We added the event to mutate the query parameters before sending to Elasticsearch. We will release this soon.

**Comment by kringkaste** [comment]
@lenvanessen As I can see in your fork, you disabled the subright and -left and added a whitespace between the term and the plus sign. If I understand this correctly, the problem only occurs when subleft is active. Or do I miss something?

**Comment by lenvanessen** [comment]
@kringkaste that's correct, for whatever reason it works then, otherwise it doesnt'
