### ISSUE TITLE
Actively maintained?

### ISSUE THREAD

**Issue by sanderpotjer** [codemonauts/craft-elasticsearch#7]
This Elasticsearch plugin looks like a great solution and from our tests it looks promising! 

However I'm slightly worried about the development. I do see some great PR suggestions without follow up and an unreleased version with a great new feature (event) waiting for over a year. 

@kringkaste are your plans to keep this plugin maintained? Thanks!

**Comment by kringkaste** [comment]
Hi, we have two customers with a hugh amount of elements in their Craft CMS and are heavy user of this plugin. So yes, for that alone, we will maintain the plugin. And yes you are right, the feature of the event should be merged and released.

**Comment by sanderpotjer** [comment]
@kringkaste great, glad to hear you have customers depending on the plugin, always a good reason to keep ik maintained 😄
